apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: stash-demo
  namespace: default
spec:
  restic: stash-demo
  volumeMounts:
  - mountPath: /recover/data
    name: recover-data
volumes:
- name: recover-data
  emptyDir: {}
