apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployments-volume-snapshot
  namespace: demo
spec:
  schedule: "* * * * *"
  driver: volumeSnapshotter
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    snapshotClassName: myVolumeSnapshotClassName
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
