kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restored-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 6Gi
  dataSource:
    kind: VolumeSnapshot
    name: pvc-2019-05-16t06-26-10-stash
    apiGroup: snapshot.storage.k8s.io