# register to intercept stash CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.stash.appscode.com
  labels:
    app: stash
webhooks:
- name: admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/admissionreviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - stash.appscode.com
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail

---
# mutating webhook for deployment
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admission.stash.appscode.com
  labels:
    app: stash
webhooks:
- name: admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/deployments
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - "apps"
    - "extensions"
    apiVersions:
    - "*"
    resources:
    - "deployments"
  failurePolicy: Fail
- name: admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/daemonsets
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - "apps"
    - "extensions"
    apiVersions:
    - "*"
    resources:
    - "daemonsets"
  failurePolicy: Fail
- name: admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/statefulsets
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - "apps"
    apiVersions:
    - "*"
    resources:
    - "statefulsets"
  failurePolicy: Fail
- name: admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/replicationcontrollers
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - ""
    apiVersions:
    - "*"
    resources:
    - "replicationcontrollers"
  failurePolicy: Fail
- name: admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/replicasets
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - "apps"
    - "extensions"
    apiVersions:
    - "*"
    resources:
    - "replicasets"
  failurePolicy: Fail
