apiVersion: appscode.com/v1beta1
kind: Backup
metadata:
  name: saumanbackup
  namespace: default
spec:
  backupSource:
    volumeName: "test-volume"
    path: /mypath
  destination:
    path: /restikvolume
    volume:
      awsElasticBlockStore:
        fsType: ext4
        volumeID: vol-***************
      name: restik-volume
  schedule: "0 * * * * *"
  tags:
  - sau
  backupRetentionPolicy:
    strategy: keep-last
    snapshotCount: 1
    prune: true
    retentionTags:
    - sau
  backupSecretRef:
    name: secret
    key: password
