apiVersion: v1
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
kind: Secret
metadata:
  creationTimestamp: 2017-06-28T14:40:55Z
  name: stash-e2e-wt54ip-local-4kat2t
  namespace: test-stash-vnciwf
  resourceVersion: "3768"
  selfLink: /api/v1/namespaces/test-stash-vnciwf/secrets/stash-e2e-wt54ip-local-4kat2t
  uid: caaefa28-5c0f-11e7-88ec-080027217e33
type: Opaque
---
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  creationTimestamp: 2017-06-28T14:40:55Z
  name: stash-nkxa4t
  namespace: test-stash-vnciwf
  resourceVersion: "3945"
  selfLink: /apis/stash.appscode.com/v1alpha1/namespaces/test-stash-vnciwf/restics/stash-nkxa4t
  uid: cab170af-5c0f-11e7-88ec-080027217e33
spec:
  backend:
    local:
      path: /repo
      volume:
        emptyDir: {}
        name: repo
    repositorySecretName: stash-e2e-wt54ip-local-4kat2t
  fileGroups:
  - path: /lib
    retentionPolicy:
      keepLastSnapshots: 5
  schedule: '@every 1m'
  selector:
    matchLabels:
      app: stash-e2e-wt54ip
status:
  backupCount: 2
  firstBackupTime: 2017-06-28T14:41:59Z
  lastBackupDuration: 1.121619348s
  lastBackupTime: 2017-06-28T14:42:59Z
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-28T14:40:55Z
  name: headless
  namespace: test-stash-vnciwf
  resourceVersion: "3771"
  selfLink: /api/v1/namespaces/test-stash-vnciwf/services/headless
  uid: cab26dd1-5c0f-11e7-88ec-080027217e33
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: stash-e2e-wt54ip
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: 2017-06-28T14:40:55Z
  generation: 1
  labels:
    app: stash-e2e-wt54ip
  name: stash-5bvewf
  namespace: test-stash-vnciwf
  resourceVersion: "3794"
  selfLink: /apis/apps/v1beta1/namespaces/test-stash-vnciwf/statefulsets/stash-5bvewf
  uid: cab50616-5c0f-11e7-88ec-080027217e33
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-e2e-wt54ip
  serviceName: headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stash-e2e-wt54ip
      name: busybox
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - schedule
        - --v=3
        - --namespace=test-stash-vnciwf
        - --name=stash-nkxa4t
        - --app=stash-5bvewf
        - --prefix-hostname=true
        image: appscode/stash:canary
        imagePullPolicy: Always
        name: stash
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: stash-scratchdir
        - mountPath: /etc
          name: stash-podinfo
        - mountPath: /repo
          name: repo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: stash-scratchdir
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
        name: stash-podinfo
      - emptyDir: {}
        name: repo
status:
  observedGeneration: 1
  replicas: 1
