apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: rest-restic
  namespace: default
spec:
  selector:
    matchLabels:
      app: rest-restic
  fileGroups:
  - path: /source/data
    retentionPolicyName: 'keep-last-5'
  backend:
    rest:
      url: https://example.com
    storageSecretName: rest-secret
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /source/data
    name: source-data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
