# Default values for stash.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
operator:
  image: appscode/stash
  pullPolicy: IfNotPresent
  tag: 0.4.1
pushgateway:
  image: prom/pushgateway
  pullPolicy: IfNotPresent
  tag: v0.4.0
## Install Default RBAC roles and bindings
rbac:
  ## If true, create & use RBAC resources
  create: false
  ## Ignored if rbac.create is true
  serviceAccountName: default
