apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stash-servicemonitor
  namespace: ${PROMETHEUS_NAMESPACE}
  labels:
    app: stash
spec:
  namespaceSelector:
    matchNames:
    - ${STASH_NAMESPACE}
  selector:
    matchLabels:
      app: stash
  endpoints:
  - port: pushgateway
