apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stash-demo
  namespace: demo
  labels:
    app: stash
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: stash
  endpoints:
  - port: pushgateway
  - port: admission
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
