{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - stash.appscode.com
  resources:
  - restics
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs: ["list", "watch", "patch"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - namespaces
  - replicationcontrollers
  verbs: ["list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", delete"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs: ["get", "create", "delete", "patch"]
{{ end }}
