apiVersion: v1
kind: Service
metadata:
  labels:
    app: stash-operator
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-stash-operator'
  namespace: '{{.Values.operator.namespace}}'
spec:
  ports:
  - name: pushgateway
    port: 56789
    protocol: TCP
    targetPort: pushgateway
  - name: http
    port: 56790
    protocol: TCP
    targetPort: http
  selector:
    app: '{{.Release.Name}}-stash-operator'
  sessionAffinity: '{{.Values.operator.sessionAffinity}}'
  type: '{{.Values.operator.serviceType}}'
