apiVersion: stash.appscode.com/v1alpha1
kind: Backup
metadata:
  name: swift-backup
  namespace: default
spec:
  selector:
    matchLabels:
      app: swift-backup
  fileGroups:
  - path: /source/data
    retentionPolicyName: 'keep-last-5'
  backend:
    swift:
      container: stashqa
      prefix: demo
    storageSecretName: swift-secret
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /source/data
    name: source-data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true

